#define f first
#define s second

#define FPS_CAP 30

#define INSIDE_WINDOW_WIDTH 512
#define INSIDE_WINDOW_HEIGHT 512
#define TOP_MARGIN 100
#define BOTTOM_MARGIN 10
#define LEFT_MARGIN 10
#define RIGHT_MARGIN 10
#define WINDOW_WIDTH (LEFT_MARGIN+INSIDE_WINDOW_WIDTH+RIGHT_MARGIN)
#define WINDOW_HEIGHT (TOP_MARGIN+INSIDE_WINDOW_HEIGHT+BOTTOM_MARGIN)

#define TILE_SIZE 32
#define MAX_TILES (INSIDE_WINDOW_WIDTH/TILE_SIZE)*(INSIDE_WINDOW_HEIGHT/TILE_SIZE)