#define f first
#define s second

#define WINDOW_WIDTH 612
#define WINDOW_HEIGHT 612
#define INSIDE_WINDOW_WIDTH 512
#define INSIDE_WINDOW_HEIGHT 512
#define TILE_SIZE 32
#define MAX_TILES (INSIDE_WINDOW_WIDTH/TILE_SIZE)*(INSIDE_WINDOW_HEIGHT/TILE_SIZE)